language: cpp
compiler: g++-4.9
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install:
  - "cd tests && \
     mv main.cpp.example main.cpp && \
     mv modules/src/TestModule.cpp.example modules/src/TestModule.cpp && \
     mv src/TestClass.cpp.example src/TestClass.cpp"

script: cd tests && make CXX=g++-4.9 clean debug && ./main
